### PR TITLE
Revert "Feature/admob support"

### PR DESCRIPTION
**Pull request by krajzler**
Reverts tenjin/tenjin-android-sdk#73

### CODE REVIEW

**Comment by krajzler** [comment]
@akarsh-tenjin I forgot to ask if I can merge this branch but since IronSource isn't merged, this also shouldn't be probably.

**Comment by akarsh-tenjin** [comment]
Since it is merged and I will close this PR

**Comment by akarsh-tenjin** [comment]
We don't need to do any revert for now. We will do some changes to the release notes as we are planning on making a aplha and beta releases.

**Comment by krajzler** [comment]
Ok thanks

**Pull request closed without merging**
