### PR TITLE
Feature/hyperbid support

### PR DESCRIPTION
**Pull request by krajzler**
Update README.md and RELEASE_NOTES.md with HyperBid info.

- [ ] Reviewed by assignee
- [ ] Branch removed

### CODE REVIEW

**Comment by akarsh-tenjin** [comment]
@krajzler Please merge master branch changes to this PR and resolve conflicts.

**Comment by krajzler** [comment]
@akarsh-tenjin Master branch is merged.

**Review by akarsh-tenjin — APPROVED** [review]
Please don't merge this PR yet. As I need to release the ironsource 1.12.10

**Comment by akarsh-tenjin** [comment]
The other PR was merged which has also the commits from this PR.
We are closing this PR

**Pull request closed without merging**
