### PR TITLE
[TENJIN-10750] Update tenjin-android-sdk to 1.12.8

### PR DESCRIPTION
**Pull request by akarsh-tenjin**
## JIRA

- https://adromance.atlassian.net/browse/TENJIN-10750

## Proposed Changes

- Update release-notes with version 1.12.8 changes
- Update tenjin aar and jar files with version 1.12.8 changes

## Steps

- [ ] Reviewed by assignee
- [ ] Branch removed

### CODE REVIEW

**Comment by makototaguchi1110** [comment]
@akarsh-tenjin this is still in review process, correct? Just checking-in, since customers might start updating the SDK with using the current master branch.

**Comment by akarsh-tenjin** [comment]
> @akarsh-tenjin this is still in review process, correct? Just checking-in, since customers might start updating the SDK with using the current master branch.

Yes it is review.
but it contains the changes of the already merged PR branch. We only need to verify that the tenjin artefacts contain the new version and working as expected.

**Comment by makototaguchi1110** [comment]
@akarsh-tenjin ok thanks for the update.

**Comment by makototaguchi1110** [comment]
@hc5duke @vanner do you mind taking a look at this pull request? Thanks!

**Review by hc5duke — APPROVED** [review]

**Pull request merged**
